name: Unit test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.5"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run unit tests
        run: |
          python -m unittest discover -s tests
